defaults:
  poll_interval: 60
  country: br

services:
  - name: Cloudflare
    slug: cloudflare
    id: 32542
    logo: /public/img/downdetector/cloudflare.svg
    poll_interval: 30
    country: com

  - name: Banco Itaú
    slug: banco-itau
    id: 33205
    logo: /public/img/downdetector/itau.svg

  - name: Nubank
    slug: nubank
    id: 33205
    logo: /public/img/downdetector/nubank.svg

  - name: Microsoft OneDrive
    slug: microsoft-onedrive
    id: 53650
    logo: /public/img/downdetector/ms365.svg
    poll_interval: 300
    country: com
